// Generated by Bisonc++ V2.7.0 on Sat, 14 Jan 2012 20:10:40 +0100

// $insert class.ih
#include "__parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {285, 2}, // 1: line ->  term EOLN
     {286, 1}, // 2: term ->  var
     {286, 1}, // 3: term ->  lambdaTerm
     {286, 1}, // 4: term ->  application
     {286, 1}, // 5: term ->  termBraced
     {286, 8}, // 6: term ->  LEFT_PARENTHESE term RIGHT_PARENTHESE LEFT_BRACKET var EQUAL term RIGHT_BRACKET
     {286, 1}, // 7: term ->  NUMBER
     {286, 1}, // 8: term ->  ADDITION
     {286, 1}, // 9: term ->  MULTIPLICATION
     {286, 1}, // 10: term ->  SUBTRACTION
     {286, 1}, // 11: term ->  TRUE
     {286, 1}, // 12: term ->  FALSE
     {286, 1}, // 13: term ->  OR
     {286, 1}, // 14: term ->  AND
     {286, 1}, // 15: term ->  NEG
     {286, 1}, // 16: term ->  LESS_OR_EQUAL
     {286, 1}, // 17: term ->  IS_ZERO
     {287, 3}, // 18: termBraced ->  LEFT_PARENTHESE term RIGHT_PARENTHESE
     {288, 1}, // 19: var ->  CHAR
     {289, 2}, // 20: varList ->  varListEmpty var
     {290, 0}, // 21: varListEmpty ->  <empty>
     {290, 2}, // 22: varListEmpty ->  varListEmpty var
     {291, 4}, // 23: lambdaTerm ->  LAMBDA varList DOT term
     {292, 2}, // 24: application ->  var var
     {292, 2}, // 25: application ->  var termBraced
     {292, 2}, // 26: application ->  termBraced var
     {292, 2}, // 27: application ->  termBraced termBraced
     {292, 2}, // 28: application ->  application var
     {292, 2}, // 29: application ->  application termBraced
     {293, 1}, // 30: line_$ ->  line
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 21} },                   
    { {       285}, {  1} }, // line           
    { {       286}, {  2} }, // term           
    { {       288}, {  3} }, // var            
    { {       291}, {  4} }, // lambdaTerm     
    { {       292}, {  5} }, // application    
    { {       287}, {  6} }, // termBraced     
    { {       261}, {  7} }, // LEFT_PARENTHESE
    { {       266}, {  8} }, // NUMBER         
    { {       267}, {  9} }, // ADDITION       
    { {       268}, { 10} }, // MULTIPLICATION 
    { {       269}, { 11} }, // SUBTRACTION    
    { {       270}, { 12} }, // TRUE           
    { {       271}, { 13} }, // FALSE          
    { {       272}, { 14} }, // OR             
    { {       273}, { 15} }, // AND            
    { {       274}, { 16} }, // NEG            
    { {       275}, { 17} }, // LESS_OR_EQUAL  
    { {       276}, { 18} }, // IS_ZERO        
    { {       257}, { 19} }, // CHAR           
    { {       259}, { 20} }, // LAMBDA         
    { {         0}, {  0} },                   
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       258}, { 21} }, // EOLN
    { {         0}, {  0} },        
};

SR__ s_3[] =
{
    { { REQ_DEF}, {  5} },                   
    { {     288}, { 22} }, // var            
    { {     287}, { 23} }, // termBraced     
    { {     257}, { 19} }, // CHAR           
    { {     261}, { 24} }, // LEFT_PARENTHESE
    { {       0}, { -2} },                   
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_5[] =
{
    { { REQ_DEF}, {  5} },                   
    { {     288}, { 25} }, // var            
    { {     287}, { 26} }, // termBraced     
    { {     257}, { 19} }, // CHAR           
    { {     261}, { 24} }, // LEFT_PARENTHESE
    { {       0}, { -4} },                   
};

SR__ s_6[] =
{
    { { REQ_DEF}, {  5} },                   
    { {     288}, { 27} }, // var            
    { {     287}, { 28} }, // termBraced     
    { {     257}, { 19} }, // CHAR           
    { {     261}, { 24} }, // LEFT_PARENTHESE
    { {       0}, { -5} },                   
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, { 20} },                   
    { {       286}, { 29} }, // term           
    { {       288}, {  3} }, // var            
    { {       291}, {  4} }, // lambdaTerm     
    { {       292}, {  5} }, // application    
    { {       287}, {  6} }, // termBraced     
    { {       261}, {  7} }, // LEFT_PARENTHESE
    { {       266}, {  8} }, // NUMBER         
    { {       267}, {  9} }, // ADDITION       
    { {       268}, { 10} }, // MULTIPLICATION 
    { {       269}, { 11} }, // SUBTRACTION    
    { {       270}, { 12} }, // TRUE           
    { {       271}, { 13} }, // FALSE          
    { {       272}, { 14} }, // OR             
    { {       273}, { 15} }, // AND            
    { {       274}, { 16} }, // NEG            
    { {       275}, { 17} }, // LESS_OR_EQUAL  
    { {       276}, { 18} }, // IS_ZERO        
    { {       257}, { 19} }, // CHAR           
    { {       259}, { 20} }, // LAMBDA         
    { {         0}, {  0} },                   
};

SR__ s_8[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_10[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_11[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_12[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_13[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_15[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_20[] =
{
    { { DEF_RED}, {   3} },                
    { {     289}, {  30} }, // varList     
    { {     290}, {  31} }, // varListEmpty
    { {       0}, { -21} },                
};

SR__ s_21[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_22[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_23[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, { 20} },                   
    { {       286}, { 32} }, // term           
    { {       288}, {  3} }, // var            
    { {       291}, {  4} }, // lambdaTerm     
    { {       292}, {  5} }, // application    
    { {       287}, {  6} }, // termBraced     
    { {       261}, {  7} }, // LEFT_PARENTHESE
    { {       266}, {  8} }, // NUMBER         
    { {       267}, {  9} }, // ADDITION       
    { {       268}, { 10} }, // MULTIPLICATION 
    { {       269}, { 11} }, // SUBTRACTION    
    { {       270}, { 12} }, // TRUE           
    { {       271}, { 13} }, // FALSE          
    { {       272}, { 14} }, // OR             
    { {       273}, { 15} }, // AND            
    { {       274}, { 16} }, // NEG            
    { {       275}, { 17} }, // LESS_OR_EQUAL  
    { {       276}, { 18} }, // IS_ZERO        
    { {       257}, { 19} }, // CHAR           
    { {       259}, { 20} }, // LAMBDA         
    { {         0}, {  0} },                   
};

SR__ s_25[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_26[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_27[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_28[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  2} },                    
    { {       262}, { 33} }, // RIGHT_PARENTHESE
    { {         0}, {  0} },                    
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       260}, { 34} }, // DOT
    { {         0}, {  0} },       
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, {  3} },        
    { {       288}, { 35} }, // var 
    { {       257}, { 19} }, // CHAR
    { {         0}, {  0} },        
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, {  2} },                    
    { {       262}, { 36} }, // RIGHT_PARENTHESE
    { {         0}, {  0} },                    
};

SR__ s_33[] =
{
    { { REQ_DEF}, {   2} },                
    { {     263}, {  37} }, // LEFT_BRACKET
    { {       0}, { -18} },                
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, { 20} },                   
    { {       286}, { 38} }, // term           
    { {       288}, {  3} }, // var            
    { {       291}, {  4} }, // lambdaTerm     
    { {       292}, {  5} }, // application    
    { {       287}, {  6} }, // termBraced     
    { {       261}, {  7} }, // LEFT_PARENTHESE
    { {       266}, {  8} }, // NUMBER         
    { {       267}, {  9} }, // ADDITION       
    { {       268}, { 10} }, // MULTIPLICATION 
    { {       269}, { 11} }, // SUBTRACTION    
    { {       270}, { 12} }, // TRUE           
    { {       271}, { 13} }, // FALSE          
    { {       272}, { 14} }, // OR             
    { {       273}, { 15} }, // AND            
    { {       274}, { 16} }, // NEG            
    { {       275}, { 17} }, // LESS_OR_EQUAL  
    { {       276}, { 18} }, // IS_ZERO        
    { {       257}, { 19} }, // CHAR           
    { {       259}, { 20} }, // LAMBDA         
    { {         0}, {  0} },                   
};

SR__ s_35[] =
{
    { { REQ_DEF}, {   2} },       
    { {     260}, { -20} }, // DOT
    { {       0}, { -22} },       
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  3} },        
    { {       288}, { 39} }, // var 
    { {       257}, { 19} }, // CHAR
    { {         0}, {  0} },        
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       265}, { 40} }, // EQUAL
    { {         0}, {  0} },         
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, { 20} },                   
    { {       286}, { 41} }, // term           
    { {       288}, {  3} }, // var            
    { {       291}, {  4} }, // lambdaTerm     
    { {       292}, {  5} }, // application    
    { {       287}, {  6} }, // termBraced     
    { {       261}, {  7} }, // LEFT_PARENTHESE
    { {       266}, {  8} }, // NUMBER         
    { {       267}, {  9} }, // ADDITION       
    { {       268}, { 10} }, // MULTIPLICATION 
    { {       269}, { 11} }, // SUBTRACTION    
    { {       270}, { 12} }, // TRUE           
    { {       271}, { 13} }, // FALSE          
    { {       272}, { 14} }, // OR             
    { {       273}, { 15} }, // AND            
    { {       274}, { 16} }, // NEG            
    { {       275}, { 17} }, // LESS_OR_EQUAL  
    { {       276}, { 18} }, // IS_ZERO        
    { {       257}, { 19} }, // CHAR           
    { {       259}, { 20} }, // LAMBDA         
    { {         0}, {  0} },                   
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, {  2} },                 
    { {       264}, { 42} }, // RIGHT_BRACKET
    { {         0}, {  0} },                 
};

SR__ s_42[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 19 "grammar.y"
        {
         d_val__.t = d_vsp__[-1].t;
         result = d_vsp__[-1].t;
         }
        break;

        case 2:
#line 26 "grammar.y"
        { d_val__.t = d_vsp__[0].t; }
        break;

        case 3:
#line 27 "grammar.y"
        { d_val__.t = d_vsp__[0].t; }
        break;

        case 4:
#line 28 "grammar.y"
        { d_val__.t = d_vsp__[0].t; }
        break;

        case 5:
#line 29 "grammar.y"
        { d_val__.t = d_vsp__[0].t; }
        break;

        case 6:
#line 31 "grammar.y"
        {
         d_val__.t = actions::substitute( d_vsp__[-6].t, (var *) d_vsp__[-3].t, d_vsp__[-1].t );
         delete d_vsp__[-6].t;
         delete d_vsp__[-3].t;
         delete d_vsp__[-1].t;
         }
        break;

        case 7:
#line 37 "grammar.y"
        { d_val__.t = churchNumeral::makeTerm(d_scanner->tokenValue()); }
        break;

        case 8:
#line 38 "grammar.y"
        { d_val__.t = churchNumeral::makeAddition(); }
        break;

        case 9:
#line 39 "grammar.y"
        { d_val__.t = churchNumeral::makeMultiplication(); }
        break;

        case 10:
#line 40 "grammar.y"
        { d_val__.t = churchNumeral::makeSubtraction(); }
        break;

        case 11:
#line 41 "grammar.y"
        { d_val__.t = churchBooleans::makeTrue(); }
        break;

        case 12:
#line 42 "grammar.y"
        { d_val__.t = churchBooleans::makeFalse(); }
        break;

        case 13:
#line 43 "grammar.y"
        { d_val__.t = churchBooleans::makeOr(); }
        break;

        case 14:
#line 44 "grammar.y"
        { d_val__.t = churchBooleans::makeAnd(); }
        break;

        case 15:
#line 45 "grammar.y"
        { d_val__.t = churchBooleans::makeNeg(); }
        break;

        case 16:
#line 46 "grammar.y"
        { d_val__.t = churchNumeral::isLessOrEqual(); }
        break;

        case 17:
#line 47 "grammar.y"
        { d_val__.t = churchNumeral::isZero(); }
        break;

        case 18:
#line 51 "grammar.y"
        { d_val__.t = d_vsp__[-1].t; }
        break;

        case 19:
#line 54 "grammar.y"
        { d_val__.t = new var((char) d_scanner->tokenValue()); }
        break;

        case 20:
#line 58 "grammar.y"
        { d_vsp__[-1].v->push_back((var *)d_vsp__[0].t); d_val__.v = d_vsp__[-1].v; }
        break;

        case 21:
#line 62 "grammar.y"
        { d_val__.v = new std::vector<var *>(); }
        break;

        case 22:
#line 63 "grammar.y"
        { d_vsp__[-1].v->push_back((var *)d_vsp__[0].t); d_val__.v = d_vsp__[-1].v; }
        break;

        case 23:
#line 68 "grammar.y"
        {
         lambdaTerm * lt = new lambdaTerm( d_vsp__[-2].v->back(), d_vsp__[0].t );
         d_vsp__[-2].v->pop_back();
         while( ! d_vsp__[-2].v->empty() )
         {
         lt = new lambdaTerm(d_vsp__[-2].v->back(), lt);
         d_vsp__[-2].v->pop_back();
         }
         delete d_vsp__[-2].v;
         d_val__.t = lt;
         }
        break;

        case 24:
#line 82 "grammar.y"
        { d_val__.t = new application(d_vsp__[-1].t,d_vsp__[0].t); }
        break;

        case 25:
#line 83 "grammar.y"
        { d_val__.t = new application(d_vsp__[-1].t,d_vsp__[0].t); }
        break;

        case 26:
#line 84 "grammar.y"
        { d_val__.t = new application(d_vsp__[-1].t,d_vsp__[0].t); }
        break;

        case 27:
#line 85 "grammar.y"
        { d_val__.t = new application(d_vsp__[-1].t,d_vsp__[0].t); }
        break;

        case 28:
#line 86 "grammar.y"
        { d_val__.t = new application(d_vsp__[-1].t,d_vsp__[0].t); }
        break;

        case 29:
#line 87 "grammar.y"
        { d_val__.t = new application(d_vsp__[-1].t,d_vsp__[0].t); }
        break;

    }
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}

